### PR TITLE
Fix MonadFail-compile error with GHC 8.6

### PR DESCRIPTION
**Pull request by obreitwi**
Trying to compile with 8.6-version of GHC results in various errors of the form:
```
./ldap-client/src/Ldap/Asn1/FromAsn1.hs:59:5: error:
    • Could not deduce (Control.Monad.Fail.MonadFail (Parser [ASN1]))
        arising from a do statement
        with the failable pattern ‘Asn1.End Asn1.Sequence’
      from the context: FromAsn1 op
        bound by the instance declaration
        at src/Ldap/Asn1/FromAsn1.hs:54:10-50
    • In a stmt of a 'do' block: Asn1.End Asn1.Sequence <- next
      In the expression:
        do Asn1.Start Asn1.Sequence <- next
           i <- fromAsn1
           op <- fromAsn1
           Asn1.End Asn1.Sequence <- next
           ....
      In an equation for ‘fromAsn1’:
          fromAsn1
            = do Asn1.Start Asn1.Sequence <- next
                 i <- fromAsn1
                 op <- fromAsn1
                 ....
   |
59 |     Asn1.End Asn1.Sequence <- next
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[...]
```

This commit implements the following suggestions in order to fix them:
* https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6#MonadFailDesugaringbydefault
* https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail#Adaptingoldcode

### CODE REVIEW

**Comment by dminuoso** [comment]
@supki Would be wonderful if you could land this and push a new version to hackage. :)
